FROM ekidd/rust-musl-builder:latest

# Install capnproto
RUN curl -O https://capnproto.org/capnproto-c++-0.6.1.tar.gz &&\
    tar zxf capnproto-c++-0.6.1.tar.gz &&\
    cd capnproto-c++-0.6.1 &&\
    ./configure &&\
    make -j8 check &&\
    sudo make install
