---
version: 2
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; rustup --version; cargo --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile --verbose
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run all tests
          command: cargo test
