---
version: 2
defaults: &defaults
  docker:
    - image: saschagrunert/build-rust:latest
workflows:
  version: 2
  build-doc-lint-test:
    jobs:
      - build
      - doc
      - lint-rustfmt
      - lint-clippy
      - test:
          requires:
            - build
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; rustup --version; cargo --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile --verbose
      - restore_cache:
          keys:
            - build-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: make build-backend build-frontend
      - save_cache:
          paths:
            - /root/.cargo/registry
            - target
          key: build-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - persist_to_workspace:
          root: target
          paths:
            - '*'
  doc:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - c2:05:c6:97:5c:9d:17:b7:c8:84:fa:6d:05:55:75:8a
      - checkout
      - run:
          name: Setup git
          command: |
            git config --global user.email mail@saschagrunert.de
            git config --global user.name "CircleCI"
      - restore_cache:
          keys:
            - doc-cache-{{ arch }}
      - run:
          name: Build documentation
          command: make build-doc
      - save_cache:
          paths:
            - /root/.cargo/registry
            - target
          key: doc-cache-{{ arch }}
      - run:
          name: Deploy documentation
          command: |
            git fetch origin gh-pages
            git checkout gh-pages
            rm -rf doc
            mv target/doc .
            git add .
            git diff-index --quiet HEAD || git commit -m 'Update documentation'
            git push origin gh-pages
  lint-rustfmt:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Rust Format
          command: make lint-rustfmt
  lint-clippy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - clippy-cache-{{ arch }}
      - run:
          name: Clippy
          command: make lint-clippy
      - save_cache:
          paths:
            - /root/.cargo/registry
            - target
          key: clippy-cache-{{ arch }}
  test:
    docker:
      - image: saschagrunert/build-rust:latest
      - image: circleci/postgres:10.4-alpine
        environment:
          POSTGRES_USER: username
          POSTGRES_DB: database
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run:
          name: Prepare database
          command: |
            sleep 15
            diesel migration run \
              --database-url postgres://username:@localhost/database
      - run:
          name: Run tests
          command: make coverage
      - run:
          name: Upload coverage report
          command: bash <(curl -s https://codecov.io/bash)
