---
version: 2
defaults: &defaults
  docker:
    - image: saschagrunert/build-rust:latest
workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; rustup --version; cargo --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile --verbose
      - restore_cache:
          keys:
            - cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target
          key: cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - persist_to_workspace:
          root: target
          paths:
            - '*'
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run:
          name: Run all tests
          command: cargo test
