table! {
    /// Representation of the `sessions` table.
    ///
    /// (Automatically generated by Diesel.)
    sessions (token) {
        /// The `token` column of the `sessions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        token -> Text,
    }
}
